channels:
  - conda-forge
  - apple
dependencies:
  - python=3.10
  - conda==22.9.0
  - pip
  - tensorflow-deps
  - notebook
  - pandas
  - matplotlib
  - scikit-learn
  - seaborn
  - keras
  - graphviz
  - pydot
