channels:
  - conda-forge
dependencies:
  - python=3.10
  - conda
  - pip
  - tensorflow<2.16
  - notebook
  - pandas
  - matplotlib
  - scikit-learn
  - ipywidgets
  - ipympl
  - scipy
  - seaborn
  - keras
  - graphviz
  - pydot
