channels:
  - apple
  - conda-forge
dependencies:
  - python=3.10
  - conda
  - pip
  - notebook
  - pandas
  - matplotlib
  - scikit-learn
  - ipywidgets
  - ipympl
  - scipy
  - seaborn
  - keras
  - graphviz
  - pydot
  - pip:
    - tensorflow-macos<2.16