channels:
  - apple
  - conda-forge
dependencies:
  - python=3.10
  - conda==22.9.0
  - pip
  - tensorflow-deps
  - notebook
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - seaborn
  - keras
  - graphviz
  - pydot
  - pip:
    - tensorflow-macos