channels:
  - conda-forge
dependencies:
  - python=3.10
  - conda
  - pip
  - tensorflow
  - notebook
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - seaborn
  - keras
  - graphviz
  - pydot
